// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext* jni;

JniContext* (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext* (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// com.example.fluttergen.ExampleKotlin
jclass _c_ExampleKotlin = NULL;

jmethodID _m_ExampleKotlin__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult ExampleKotlin__new0() {
  load_env();
  load_class_global_ref(&_c_ExampleKotlin,
                        "com/example/fluttergen/ExampleKotlin");
  if (_c_ExampleKotlin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_ExampleKotlin, &_m_ExampleKotlin__new0, "<init>", "()V");
  if (_m_ExampleKotlin__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result =
      (*jniEnv)->NewObject(jniEnv, _c_ExampleKotlin, _m_ExampleKotlin__new0);
  return to_global_ref_result(_result);
}

jmethodID _m_ExampleKotlin__sumKtc = NULL;
FFI_PLUGIN_EXPORT
JniResult ExampleKotlin__sumKtc(jobject self_, int32_t i, int32_t i1) {
  load_env();
  load_class_global_ref(&_c_ExampleKotlin,
                        "com/example/fluttergen/ExampleKotlin");
  if (_c_ExampleKotlin == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_ExampleKotlin, &_m_ExampleKotlin__sumKtc, "sumKtc", "(II)I");
  if (_m_ExampleKotlin__sumKtc == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  int32_t _result =
      (*jniEnv)->CallIntMethod(jniEnv, self_, _m_ExampleKotlin__sumKtc, i, i1);
  return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}
